version: '3'
services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # Map the port
    volumes:
      - .:/app  
    environment:
      - WATCHPACK_POLLING=true # For sincronizing the changes
    stdin_open: true
    tty: true
